/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.organizacija;

import controller.ClientController;
import domain.Organizacija;
import forms.MainForm;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import models.TableModelOrganizacije;


/**
 *
 * @author marek
 */
public class FormPretragaOrganizacije extends javax.swing.JDialog {
    
    public FormPretragaOrganizacije(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TableModelOrganizacije model = new TableModelOrganizacije(this);
        Thread th = new Thread(model);
        th.start();
        tblOrganizacija.setModel(model);
        
    }

    public JTable getTblOrganizacija() {
        return tblOrganizacija;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnDetalji = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrganizacija = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organizacije");
        setResizable(false);

        jLabel1.setText("Pretraga:");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 14));

        txtPretraga.setMaximumSize(new java.awt.Dimension(300, 25));
        txtPretraga.setMinimumSize(new java.awt.Dimension(100, 25));
        txtPretraga.setPreferredSize(new java.awt.Dimension(200, 25));
        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPretragaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretragaKeyReleased(evt);
            }
        });

        btnDetalji.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetalji.setText("Detalji organizacije");
        btnDetalji.setMaximumSize(new java.awt.Dimension(400, 35));
        btnDetalji.setMinimumSize(new java.awt.Dimension(100, 35));
        btnDetalji.setPreferredSize(new java.awt.Dimension(200, 35));
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });
        btnDetalji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDetaljiKeyPressed(evt);
            }
        });

        tblOrganizacija.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOrganizacija);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyReleased
        String param = txtPretraga.getText();
        TableModelOrganizacije tmo = (TableModelOrganizacije) tblOrganizacija.getModel();
        tmo.setParametar(param);
        if (tmo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Nema organizacije za zadati kriterijum!");
            txtPretraga.setText("");
            tmo.setParametar("");
            txtPretraga.requestFocusInWindow();
            txtPretraga.selectAll();
        }
    }//GEN-LAST:event_txtPretragaKeyReleased

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        detalji();
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void txtPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            if (tblOrganizacija.getRowCount() == 0) {
                return ;
            }
            tblOrganizacija.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtPretragaKeyPressed

    private void btnDetaljiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDetaljiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnDetalji.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            txtPretraga.requestFocusInWindow();
            txtPretraga.selectAll();
        }
    }//GEN-LAST:event_btnDetaljiKeyPressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrganizacija;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        TableModelOrganizacije model = (TableModelOrganizacije) tblOrganizacija.getModel();
        model.refreshTable();
    }

    private void detalji() {
        int row = tblOrganizacija.getSelectedRow();
        if(row >= 0){
            try {
                Organizacija o =
                        ((TableModelOrganizacije)tblOrganizacija.getModel()).getSelectedOrganizacija(row);
                Organizacija organizacija = ClientController.getInstance().getOrganizacija(o);
                FormDetaljiOrganizacije fdo = new FormDetaljiOrganizacije(this, rootPaneCheckingEnabled, organizacija);
                fdo.setLocationRelativeTo(null);
                fdo.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Greska prilikom ucitavanja organizacije: " + e.getMessage());
                e.printStackTrace();
            }
        } else{
            JOptionPane.showMessageDialog(rootPane, "Nije oznacena nijedna organizacija u tabeli!");
        }
    }


}
